#!/bin/bash

  # This function takes either a name/partial name or a full bluetooth MAC address.
  # If it sees the name in your paired devices it will try to toggle between connecting to that device, or disconnecting from it.
  # If it doesn't see your device paired but you passed a full bluetooth MAC address, it will scan for that address and try to pair/connect with it.


  # I bound Ctrl+Alt+A to "bash -i -c 'bluetoothQuickConnectDisconnect airpods'" (get it, Ctrl+Alt+A for Airpods) to steal/unsteal my airpods from my phone.
  # But also made an alias for that command too.

function bluetoothQuickConnectDisconnect() {
  function printer {
    [ -n "$1" ] && msg="${1}" || msg=''
    [ -n "$2" ] && ms="${2}" || ms=5000
    [ -n "$3" ] && actionFlag='-A' action="$3"

    >&2 echo "$msg"
    eval $(notify-send "$msg" -t $ms $actionFlag "$action" 2>/dev/null) &
  }

  if [ -z "$1" ]
  then
    printer "You must give either a device name arg or bluetooth MAC to pair with." 5000 "blueman-manager=Open Blueman?"
    return 1
  else
    bluetoothDevice=$1
  fi
  allPairedDevices="$(bluetoothctl devices)"


  if result=$(grep -E -m1 -i "$bluetoothDevice" <<< "$allPairedDevices")
  then
    address="$(cut -f2 -d' ' <<< $result)"
    if bluetoothctl info $address |grep -q 'Connected: no'
    then
      bluetoothctl connect $address
    else
      bluetoothctl disconnect $address
    fi
  elif [[ "$bluetoothDevice" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]]
    then
       printer "$bluetoothDevice not paired, is MAC, initiating scan..."
       timeout -s HUP 10 stdbuf -oL bluetoothctl scan on | grep -m1 -i "$bluetoothDevice" && \
         bluetoothctl pair $bluetoothDevice && \
         bluetoothctl connect $bluetoothDevice
       if [ "$?" -gt "127" ]
       then
         printer "Could not find $bluetoothDevice in scan. Giving up." 5000 "blueman-manager=Open Blueman?"
       fi
  else
    printer "$bluetoothDevice not paired." 5000 "blueman-manager=Open Blueman?"
  fi
}; alias Airpods=airpods connectAirpods=airpods connectairpods=airpods airpods='bluetoothQuickConnectDisconnect Airpods'
