#!/bin/bash

function colorPS1 {
  while [ $# -gt 0 ]
  do
    case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
      -color)
        color=$2
        shift
      ;;
      -location)
        location=$2
        shift
      ;;
      -modifier)
        modifier=$2
        shift
      ;;
      -target)
        target=$(sed -e 's/\\/\\\\/g' -e 's/\ /\\ /g' -e 's/\$/\\$/g' <<< $2)
        shift
      ;;
      *)
        echo "Unknown argument $1 for the colorPS1 bashrc function"
        shift
      ;;
    esac
    shift
  done

  [ -z "$modifier" ] && modifier=none
  modifierToApply=${modifiers[$modifier]}

  [ -z "$color" ] && color=none
  colorToApply=${colors[$color]}

  [[ "$location" == "background" ]] && colorToApply=$(($colorToApply + 10)) # Background offset

  application="\\\[\\\e[${modifierToApply}\;${colorToApply}m\\\]"
  end="\\\[\\\e[0m\\\] " # Always clear after coloring something


  PS1=$(sed "s,${target},${application}${target}${end},g" <<< "$PS1")
}
