#!/bin/bash

function grepUniqOrdered {
  [ -n "$1" ] || { >&2 echo -e "Need at least one file as argument.\nRemoves duplicate lines from file but keeps order" ; return 1 ;}
  awk -F '\n' '!a[$1 FS $2]++' ${@} # Ignore any duplicate lines while reading out all provided files.
}; alias dedupe=grepUniqOrdered dedup=grepUniqOrdered
# Useful for fixing bash history from snapshots with something like:
# 'HISTFILE=/dev/null ; dedup /home/.zfs/snapshot/*/$USER/.bash_history > .bash_history'
