#!/bin/bash

function mkRandom {
  if [[ -n "$1" ]] && [[ "$1" =~ [0-9]+ ]]
  then
    len="$1"
  else
    len=16
  fi
  tr -dc A-Za-z0-9 < /dev/urandom | head -c$len
  echo
}; alias mkrandom=mkRandom
