#!/bin/bash

# A vault wrapper to easily read kv/totp secret paths to the clipboard on-demand.
function readVaultClipboard {
  if [[ "$1" == *"totp"* ]]
  then
    jqpattern='.data.code'
    vaultargs='read'
  else
    [ -z "$2" ] && { echo "Need a second argument for which Key to read of secret" ; return 1 ;}
    jqpattern=".data.data.$2"
    vaultargs='kv get'
  fi
  vaultResult="$(vault $vaultargs -format json $1)"
  vaultExitCode=$?

  if [ $vaultExitCode -eq 0 ]
  then
    stripResult=$(jq -r "$jqpattern" <<< "${vaultResult}" | tr -d '\n')
  else
    echo "ERR reading vault!"
  fi

  if [ -n "$DISPLAY" ]
  then
    xclip -sel clip <<< ${stripResult}
    echo "OK - sent to clipboard"
  else
    echo "ERR - display variable not set, printing here:"
    echo -e "\t${stripResult}"
  fi
  unset stripResult
}
